all:
  hosts:
    gentoo_live:
      ansible_connection: ssh
      ansible_user: root
      ansible_python_interpreter: auto_silent
    gentoo_installed:
      ansible_connection: ssh
      ansible_user: root
      ansible_python_interpreter: auto_silent
    gentoo_desktop:
      ansible_connection: ssh
      ansible_user: root
      ansible_python_interpreter: auto_silent
