---
desktop_sway_core_packages:
  - sys-apps/dbus
  - gui-wm/sway
  - gui-apps/foot

desktop_sway_recommended_packages:
  - gui-apps/waybar
  - gui-apps/wofi
  - gui-apps/wl-clipboard
  - gui-apps/grim
  - gui-apps/slurp

desktop_sway_portal_packages:
  - sys-apps/xdg-desktop-portal
  - gui-libs/xdg-desktop-portal-wlr

desktop_sway_validation_commands:
  - name: sway
    commands:
      - sway
  - name: foot
    commands:
      - foot

desktop_sway_session_command: exec dbus-run-session -- sway
