---
- name: Install post-install desktop profile
  hosts: gentoo_desktop
  gather_facts: true
  vars_files:
    - ../group_vars/desktop_i3_x11.yml
  roles:
    - role: post_install/desktop_common
    - role: post_install/desktop_i3_x11
