#!/usr/bin/env python3
"""Generate the Gentoo Handbook traceability report."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


DEFAULT_INPUT = Path("config/handbook-traceability.json")
DEFAULT_OUTPUT = Path("docs/handbook-traceability.md")
REQUIRED_FIELDS = {
    "phase",
    "handbook_section",
    "make_targets",
    "ansible_roles",
    "status",
    "safety_gates",
    "validation_evidence",
    "deviations",
    "openspec_refs"
}


def die(message: str) -> None:
    print(f"handbook-trace: CONFIG_INVALID: {message}", file=sys.stderr)
    raise SystemExit(1)


def load_model(path: Path) -> dict[str, Any]:
    if not path.is_file() or path.is_symlink():
        die(f"traceability input is missing or unsafe: {path}")
    try:
        model = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        die(f"traceability input is not valid JSON: {exc}")
    if not isinstance(model, dict):
        die("traceability input must be a JSON object")
    entries = model.get("entries")
    if not isinstance(entries, list) or not entries:
        die("traceability input must contain non-empty entries")
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            die(f"entry {index} must be an object")
        missing = REQUIRED_FIELDS.difference(entry)
        if missing:
            die(f"entry {index} is missing fields: {', '.join(sorted(missing))}")
        for field in ("make_targets", "ansible_roles", "safety_gates", "validation_evidence", "deviations", "openspec_refs"):
            if not isinstance(entry[field], list):
                die(f"entry {index} field {field} must be a list")
    return model


def format_list(values: list[Any]) -> str:
    if not values:
        return "_None._"
    return "\n".join(f"- {value}" for value in values)


def render_markdown(model: dict[str, Any]) -> str:
    handbook_url = model.get("handbook_url", "https://wiki.gentoo.org/wiki/Handbook:AMD64")
    lines = [
        "# Gentoo Handbook Traceability",
        "",
        "This report maps `gentoo-ai-installer` workflows to the official Gentoo AMD64 Handbook baseline.",
        "",
        f"Handbook baseline: {handbook_url}",
        "",
        "Generated by `make handbook-trace` from `config/handbook-traceability.json`.",
        "",
        "## Metadata Fields",
        "",
        "Each entry records phase, Handbook section, Makefile targets, Ansible roles, implementation status, safety gates, validation evidence, project deviations, and OpenSpec references.",
        "",
        "## Phase Map",
        "",
        "| Phase | Status | Handbook Section | Make Targets | Ansible Roles |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in model["entries"]:
        targets = "<br>".join(f"`make {target}`" for target in entry["make_targets"]) or "_None_"
        roles = "<br>".join(f"`{role}`" for role in entry["ansible_roles"]) or "_None_"
        lines.append(f"| {entry['phase']} | {entry['status']} | {entry['handbook_section']} | {targets} | {roles} |")

    lines.extend(["", "## Details", ""])
    for entry in model["entries"]:
        lines.extend([
            f"### {entry['phase']}",
            "",
            f"- Status: `{entry['status']}`",
            f"- Handbook section: {entry['handbook_section']}",
            "",
            "Make targets:",
            format_list([f"make {target}" for target in entry["make_targets"]]),
            "",
            "Ansible roles:",
            format_list(entry["ansible_roles"]),
            "",
            "Safety gates:",
            format_list(entry["safety_gates"]),
            "",
            "Validation evidence:",
            format_list(entry["validation_evidence"]),
            "",
            "Project-specific deviations:",
            format_list(entry["deviations"]),
            "",
            "OpenSpec references:",
            format_list(entry["openspec_refs"]),
            "",
        ])
    return "\n".join(lines)


def command_generate(args: argparse.Namespace) -> None:
    model = load_model(args.input)
    rendered = render_markdown(model)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered + "\n", encoding="utf-8")
    print(f"Handbook traceability report written: {args.output}")
    print(f"Entries: {len(model['entries'])}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.set_defaults(func=command_generate)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
